# Generated by Django 4.2.7 on 2025-08-11 09:37

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم - عربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم - إنجليزي')),
                ('name_tr', models.CharField(max_length=100, verbose_name='الاسم - تركي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'تصنيف الأخبار',
                'verbose_name_plural': 'تصنيفات الأخبار',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان - عربي')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان - إنجليزي')),
                ('title_tr', models.CharField(max_length=200, verbose_name='العنوان - تركي')),
                ('content_ar', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='المحتوى - عربي')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='المحتوى - إنجليزي')),
                ('content_tr', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='المحتوى - تركي')),
                ('excerpt_ar', models.TextField(max_length=300, verbose_name='ملخص - عربي')),
                ('excerpt_en', models.TextField(max_length=300, verbose_name='ملخص - إنجليزي')),
                ('excerpt_tr', models.TextField(max_length=300, verbose_name='ملخص - تركي')),
                ('featured_image', models.ImageField(upload_to='news/', verbose_name='الصورة البارزة')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-published_at'],
            },
        ),
    ]
