# Generated by Django 4.2.7 on 2025-08-11 09:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_ar', models.CharField(default='مؤسسة ركائز', max_length=100, verbose_name='اسم الموقع - عربي')),
                ('site_name_en', models.CharField(default='Rakayez Foundation', max_length=100, verbose_name='اسم الموقع - إنجليزي')),
                ('site_name_tr', models.CharField(default='Rakayez Vakfı', max_length=100, verbose_name='اسم الموقع - تركي')),
                ('logo', models.ImageField(upload_to='settings/', verbose_name='الشعار')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/', verbose_name='أيقونة المتصفح')),
                ('about_ar', ckeditor.fields.RichTextField(verbose_name='نبذة عن المؤسسة - عربي')),
                ('about_en', ckeditor.fields.RichTextField(verbose_name='نبذة عن المؤسسة - إنجليزي')),
                ('about_tr', ckeditor.fields.RichTextField(verbose_name='نبذة عن المؤسسة - تركي')),
                ('vision_ar', ckeditor.fields.RichTextField(verbose_name='الرؤية - عربي')),
                ('vision_en', ckeditor.fields.RichTextField(verbose_name='الرؤية - إنجليزي')),
                ('vision_tr', ckeditor.fields.RichTextField(verbose_name='الرؤية - تركي')),
                ('mission_ar', ckeditor.fields.RichTextField(verbose_name='الرسالة - عربي')),
                ('mission_en', ckeditor.fields.RichTextField(verbose_name='الرسالة - إنجليزي')),
                ('mission_tr', ckeditor.fields.RichTextField(verbose_name='الرسالة - تركي')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('address_ar', models.TextField(verbose_name='العنوان - عربي')),
                ('address_en', models.TextField(verbose_name='العنوان - إنجليزي')),
                ('address_tr', models.TextField(verbose_name='العنوان - تركي')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, verbose_name='إنستغرام')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكدإن')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name='خريطة جوجل')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
