# Generated by Django 4.2.7 on 2025-08-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم - عربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم - إنجليزي')),
                ('name_tr', models.CharField(max_length=100, verbose_name='الاسم - تركي')),
                ('position_ar', models.CharField(max_length=100, verbose_name='المنصب - عربي')),
                ('position_en', models.CharField(max_length=100, verbose_name='المنصب - إنجليزي')),
                ('position_tr', models.CharField(max_length=100, verbose_name='المنصب - تركي')),
                ('bio_ar', models.TextField(blank=True, verbose_name='نبذة - عربي')),
                ('bio_en', models.TextField(blank=True, verbose_name='نبذة - إنجليزي')),
                ('bio_tr', models.TextField(blank=True, verbose_name='نبذة - تركي')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='الصورة')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكدإن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'عضو الفريق',
                'verbose_name_plural': 'أعضاء الفريق',
                'ordering': ['order', 'name_ar'],
            },
        ),
    ]
