# Generated by Django 4.2.7 on 2025-08-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_service_cost_service_duration_and_more'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='services.service', verbose_name='الخدمة'),
        ),
    ]
