# Generated by Django 4.2.7 on 2025-08-11 09:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان - عربي')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان - إنجليزي')),
                ('title_tr', models.CharField(max_length=200, verbose_name='العنوان - تركي')),
                ('description_ar', ckeditor.fields.RichTextField(verbose_name='الوصف - عربي')),
                ('description_en', ckeditor.fields.RichTextField(verbose_name='الوصف - إنجليزي')),
                ('description_tr', ckeditor.fields.RichTextField(verbose_name='الوصف - تركي')),
                ('image', models.ImageField(upload_to='services/', verbose_name='الصورة')),
                ('icon', models.CharField(blank=True, help_text='اسم الأيقونة من Font Awesome', max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['order', 'title_ar'],
            },
        ),
    ]
