# Generated by Django 4.2.7 on 2025-08-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم - عربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم - إنجليزي')),
                ('name_tr', models.CharField(max_length=100, verbose_name='الاسم - تركي')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف - عربي')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف - إنجليزي')),
                ('description_tr', models.TextField(blank=True, verbose_name='الوصف - تركي')),
                ('icon', models.CharField(blank=True, help_text='اسم الأيقونة من Font Awesome', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#6b73ff', help_text='كود اللون HEX', max_length=7, verbose_name='اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'فئة الخدمات',
                'verbose_name_plural': 'فئات الخدمات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.CharField(blank=True, max_length=100, verbose_name='التكلفة'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدة الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='excerpt_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='ملخص - عربي'),
        ),
        migrations.AddField(
            model_name='service',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='ملخص - إنجليزي'),
        ),
        migrations.AddField(
            model_name='service',
            name='excerpt_tr',
            field=models.TextField(blank=True, max_length=300, verbose_name='ملخص - تركي'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='ميزات الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='مجانية'),
        ),
        migrations.AddField(
            model_name='service',
            name='prerequisites',
            field=models.TextField(blank=True, verbose_name='المتطلبات المسبقة'),
        ),
        migrations.AddField(
            model_name='service',
            name='requests_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات'),
        ),
        migrations.AddField(
            model_name='service',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200, verbose_name='الفئة المستهدفة'),
        ),
        migrations.AddField(
            model_name='service',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='الصورة'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='الفئة'),
        ),
    ]
