# Generated by Django 4.2.7 on 2025-08-24 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=100, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='العنوان بالإنجليزية')),
                ('widget_type', models.CharField(choices=[('stats', 'إحصائيات'), ('chart', 'رسم بياني'), ('table', 'جدول'), ('quick_actions', 'إجراءات سريعة')], max_length=50, verbose_name='نوع العنصر')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='الموضع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'عنصر لوحة التحكم',
                'verbose_name_plural': 'عناصر لوحة التحكم',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_ar', models.CharField(max_length=100, verbose_name='اسم الموقع بالعربية')),
                ('site_name_en', models.CharField(blank=True, max_length=100, verbose_name='اسم الموقع بالإنجليزية')),
                ('tagline_ar', models.CharField(blank=True, max_length=200, verbose_name='الشعار بالعربية')),
                ('tagline_en', models.CharField(blank=True, max_length=200, verbose_name='الشعار بالإنجليزية')),
                ('about_ar', models.TextField(blank=True, verbose_name='عن الموقع بالعربية')),
                ('about_en', models.TextField(blank=True, verbose_name='عن الموقع بالإنجليزية')),
                ('logo', models.ImageField(blank=True, upload_to='settings/', verbose_name='الشعار')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/', verbose_name='أيقونة المتصفح')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='بريد التواصل')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف التواصل')),
                ('address_ar', models.TextField(blank=True, verbose_name='العنوان بالعربية')),
                ('address_en', models.TextField(blank=True, verbose_name='العنوان بالإنجليزية')),
                ('facebook_url', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('twitter_url', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('instagram_url', models.URLField(blank=True, verbose_name='رابط إنستغرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='رابط لينكد إن')),
                ('youtube_url', models.URLField(blank=True, verbose_name='رابط يوتيوب')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='رقم واتساب')),
                ('meta_description_ar', models.TextField(blank=True, max_length=160, verbose_name='وصف الموقع للبحث (عربي)')),
                ('meta_description_en', models.TextField(blank=True, max_length=160, verbose_name='وصف الموقع للبحث (إنجليزي)')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='الكلمات المفتاحية')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='معرف جوجل التحليلات')),
                ('smtp_host', models.CharField(blank=True, max_length=100, verbose_name='خادم البريد')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='منفذ البريد')),
                ('smtp_username', models.CharField(blank=True, max_length=100, verbose_name='اسم مستخدم البريد')),
                ('smtp_password', models.CharField(blank=True, max_length=100, verbose_name='كلمة مرور البريد')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='استخدام TLS')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='الإجراء')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='نوع النموذج')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نشاط المستخدم',
                'verbose_name_plural': 'أنشطة المستخدمين',
                'ordering': ['-timestamp'],
            },
        ),
    ]
